### ISSUE TITLE
[BUG] Unity struct references aren't drawn correctly in inspector

### ISSUE THREAD

**Issue by KurtGokhan** [unity-atoms/unity-atoms#367] opened 2022-08-22 20:50 UTC
**Describe the bug**
When `Use Value` is selected, value is drawn over the label and usage dropdown. I guess this only happens for struct references like Vector2Reference etc.

**To Reproduce**
1. Create a MonoBehavior with `Vector2Reference` field
2. Go to its inspector and observe how that field is drawn

**Expected behavior**
The dropdown for usage should be visible

**Screenshots**

![image](https://user-images.githubusercontent.com/6034931/186016163-f4de0d24-fc9f-46ab-a960-6e122b661f78.png)

**Environment**
 - OS: Windows
 - Unity Version [e.g. 2022.1]
 - Version of Unity Atoms 4.4.5

**Additional context**
Already fixed in PR #368

**Comment by soraphis** [comment] 2022-08-22 21:48
duplicate of #353
this is already fixed on canary with #359

**Closed by soraphis** 2022-08-22 21:48 UTC
Labels: bug, duplicate
