### ISSUE TITLE
[BUG] Generator asset fails to generate some `UnityEngine` types.

### ISSUE THREAD

**Issue by Esildor** [unity-atoms/unity-atoms#408] opened 2023-07-10 16:52 UTC
**Describe the bug**
Trying to generate types from the `UnityEngine` namespace doesn't work, or provides weird results. For example, in the case of `UnityEngine.Camera` some variable scripts are generated, but they are missing the _Camera_ prefix. See screenshot below. In the case of `UnityEngine.Grid` it generates the subclass, `GridLayout`. 

**To Reproduce**
1. Create an `Atom Generator` asset
2. Paste this line into the `Full Qualified Name` field
_UnityEngine.Camera, UnityEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null_
or
_UnityEngine.Grid, UnityEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null_

**Expected behavior**
Unity types are able to be generated via the `Atom Generator` asset

**Screenshots**
Results
![image](https://github.com/unity-atoms/unity-atoms/assets/5234969/b2eaec70-53b6-42c2-9a9e-dd271170a2fd)

**Environment**
 - OS: Windows 11
 - Unity Version: 2021.3.24f1
 - Version of Unity Atoms: `canary` branch

**Comment by soraphis** [comment] 2023-07-12 17:22
hm ... can't reproduce with unity 2022.2 and Atoms `canary` branch...

**Comment by AdamRamberg** [comment] 2023-07-19 17:42
Fixed in #409

**Closed by AdamRamberg** 2023-07-19 17:42 UTC
Labels: bug, has PR
